---

- name: update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

# - name: Install Docker Dependencies
#   apt: name={{ item }} state=latest update_cache=yes
#   with_items:
#     - apt-transport-https
#     - ca-certificates
#     - curl
#     - software-properties-common 
#   tags: docker

# - name: Get Docker gpg key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present
#   tags: docker

# - name: Ddd Docker packages to Repository
#   apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
#   tags: docker
  
# - name: Install Docker-CE
#   apt: name="docker-ce" state=latest update_cache=yes
#   tags: docker

# - name: Enable service docker
#   systemd:
#     name: docker
#     state: started
#     enabled: yes

# - name: Add pi user to docker group
#   user:
#     name: pi
#     groups:
#       - docker
#     append: yes
- name: Download docker install script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
  
- name: Run docker script
  ansible.builtin.shell:
    cmd: cat /tmp/get-docker.sh | sh -s -- -y
# - name: Instal python-pip
#   apt:
#     name: "python-pip"
#     state: latest
#     update_cache: yes


# - name: Install docker-compose via pip"
#   pip:
#     name: docker-compose


- name: Enable service docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add pi user to docker group
  user:
    name: pi
    groups:
      - docker
    append: yes

