---
- name: Add Workers to the Swarm
  shell: "docker swarm join --token {{ hostvars['192.168.1.44']['worker_token']['stdout'] }} {{ hostvars['192.168.1.44']['ansible_default_ipv4']['address'] }}:2377"
  tags: swarm